### PR TITLE
Address TextureAtlas issues

### PR DESCRIPTION
**Pull request by cursedcoder**
including fix for a nasty deprecated method

https://github.com/pixijs/pixi-spine/blob/master/CONTRIBUTING.md seems to be quite outdated, so I'm unsure about `build` dir

ping @ivanpopelyshev

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
Hm, cant we just pass "loader.resources" into texturehash directly?

**Comment by cursedcoder** [comment]
@ivanpopelyshev good idea, but it's not possible, since Atlas will try to load them into regions.

If you want, I can modify `addTextureHash` for the feature you described.

**Comment by ivanpopelyshev** [comment]
Agree.

Yeah, but if we load pixi atlas instead of spine atlas, we can just specify "loader.resources["atlas"].textures , that's the trick i want to show too

**Comment by cursedcoder** [comment]
@ivanpopelyshev so let's support both?

**Comment by ivanpopelyshev** [comment]
I think we have to incorporate that one as soon as its merged: https://github.com/pixijs/pixi.js/pull/3676

**Comment by cursedcoder** [comment]
Sure, let's do.

**Pull request merged**
