### PR TITLE
Added "standalone" argument to `browserify` call.

### PR DESCRIPTION
**Pull request by probityrules**
This appends a semi-colon to the debug build allowing for proper file concatenation to fix https://github.com/pixijs/pixi-spine/issues/113.

I'm not familiar with the gulp compilation process, but I found another project with a similar issue and resolution here: https://github.com/jessepollak/card/issues/103. I'm uncertain whether this will cause any unwanted side-effects, but the updated `pixi-spine.js` is working fine for me.

I included the built files for your perusal since this was a change to the build process itself.

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
Nice! Can you look where is that line "PIXI.spine = ..." in our sources and remove it?

**Comment by probityrules** [comment]
I went ahead and removed it. I would imagine it wouldn't be needed here unless someone is using the source code directly instead of the bin distributables: Is that a use case?

**Comment by ivanpopelyshev** [comment]
Please undo it, but place a comment "Its supposed to be there for people/plugins who use plugin both through require and as a plugin."

**Comment by ivanpopelyshev** [comment]
Nice ! Thank you ! Please, next time, don't add binary files there, it will be better if i build them, 

I want to move binaries in other repository anyway, and fighting with @GoodBoyDigital and @englercj about it.

**Comment by probityrules** [comment]
I'll keep that in mind; thanks!

**Comment by englercj** [comment]
> I want to move binaries in other repository anyway, and fighting with @GoodBoyDigital and @englercj about it.

Stop being an ass, it is tiring.

**Comment by ivanpopelyshev** [comment]
@englercj :) There's a thing about travis, somebody said that it can be used for builds on s3. I wanna try that :)

**Pull request merged**
