### PR TITLE
Fix file type check for Pixi.js 3

### PR DESCRIPTION
**Pull request by gatsinski**
Pixi.js 3 uses resource-loader v1.6.4 and there is no Resource.TYPE enumeration. It is introduced with v2.0.0.

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
ok, im finally home and i finally can comment on this : supporting pixi-3 is difficult because i dont remember it.

1. there is difference in loader, yes, thank you for PR
2. there might be difference in Texture rotation algorithm.

3. I will have to update it every time something happens in spine-ts 3.8 !!! Its already difficult to track it for pixi4-spine3.8 at the same time as maeter.

I can create separate branch for you, and you'll make PR's there. Please rebase to `pixi3-spine3.8`

**Comment by gatsinski** [comment]
The CI fails because of incompatible dependencies. They are fixed in my previous PR #350. When 350 is merged, I will rebase.

**Comment by gatsinski** [comment]
I just rebased. The Travis build should pass now.

**Comment by gatsinski** [comment]
I see that you created pixi3-spine3.8 before merging #350. I introduced it to this PR. Otherwise, the build will fail.

**Comment by gatsinski** [comment]
Our team is experimenting with pixi4-spine3.8 on Pixi.js 3 and everything looks good so far except for a strange problem with one of the animations but it's too early to blame pixi-spine for it. We are still investigating.

**Comment by gatsinski** [comment]
Can we get this merged? It's the only thing preventing the normal use of Pixi.js 3 with Spine 3.8. I don't know about the Texture rotation algorithm but so far everything works correctly. 

And don't bother about keeping track of what's going on with Spine 3.8. Our team can support Pixi.js 3 and 4 as long as we continue to use them in the company and even beyond. I will do my best for the sake of open-source. :)

**Pull request merged**
