### PR TITLE
Prevent error for use with custom built versions of PIXI that do not have the Loader module

### PR DESCRIPTION
**Pull request by kane-mason**
Added a simple 'if' to check if Loaders module is present. Did not alter the unit test as it would require rewriting, can be done on request if needed.

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
It does work for you, right?

**Comment by kane-mason** [comment]
Yes! Game loads and the spine animations play out as expected

**Comment by ivanpopelyshev** [comment]
ok gonna release it today

**Comment by kane-mason** [comment]
awesome thanks so much

**Pull request merged**
