### PR TITLE
fix #290

### LINKED ISSUE #290: Root Bone rotation flipped in 1.5.20
Hi,  

Setting rotation on a root bone, is behaving differently on latest version 1.5.20 

Eg.  Set the rotation of a root Bone of a skeleton 30 deg ( in spine IDE, rotates whole skeleton anticlockwise 30)

1.5.19 is correct:  
https://www.pixiplayground.com/#/edit/KMb5DIicjvjvGbcgcfSOb

1.5.20 ( 30 becomes -30, rotating clockwise instead )
https://www.pixiplayground.com/#/edit/32hwIwe42aY3RujwFX~af

### PR DESCRIPTION
**Pull request by rich-earth**
-Figured out the yDown flipping / root rotation 

-Can we have check in update() after state.apply,  in case an animation event caused the spine to be destroyed.

### CODE REVIEW

**Comment by Dairnon** [comment]
Has this been merged yet?

**Comment by ivanpopelyshev** [comment]
I want to make my own version of this tomorrow, with less changes.

**Comment by ivanpopelyshev** [comment]
OK, I'm merging it but we need a demo that shows everything. Because the change in `NoScaleOrReflection` looks like a fix that has to be in spine-ts itself.

Also, `shearX` and `shearY` can be reversed here , I dont like that code too but we can work on it.

**Comment by ivanpopelyshev** [comment]
I contacted @badlogic about it.

**Comment by ivanpopelyshev** [comment]
OK, 1.5.22, we'll find what else to fix there later.

**Comment by ivanpopelyshev** [comment]
Well, shit, it was a real bug in spine-ts: EsotericSoftware/spine-runtimes#1379

Your rotation = -rotation fix ok only for scaleX != scaleY :)

next time ill spend more time on that kind of issue so we can report them properly.

**Pull request merged**
