### PR TITLE
PIXI not defined when in a closure

### PR DESCRIPTION
**Pull request by Adamfsk**
Fixes https://github.com/pixijs/pixi-spine/issues/130 which was causing a runtime error for me on PIXI.loaders.Loader.addPixiMiddleware(atlasParser); in the atlasParser function in loaders.ts.

Fix: Defined Spine as a separate namespace, and this is then assigned to PIXI.spine as suggested by @uorbe001

I know this may not be accepted, but it might help if you haven't already got a solution :)

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
Ok, I'm gonna try it. Actually making it the separate namespace is good.

**Comment by ivanpopelyshev** [comment]
@Adamfsk please check the latest version for you case :) If it works, i'll publish new version.

**Comment by Adamfsk** [comment]
Hey, I've just tested it out, and it does work, but there's one possible issue with both changes that you need to be aware of before deciding to include the change;

The new @types/Pixi.js typings is now being included at compile time. If the user has a project using typings or tsd instead, this will create PIXI duplicate reference errors if they include pixi-spine in their project.

I'm not sure on your current coding standards, so you will need to decide if it's better to include this as a note in the docs, that @types reference must be used in projects using spine from now on, OR that this needs to be fixed somehow to remove this backwards-compatibility issue.

**Comment by ivanpopelyshev** [comment]
Right, that's an issue. Yes, I'll add lines about @types. Thank you!

**Pull request closed without merging**
