### PR TITLE
 add diffuse group for hackAttachmentGroups 

### PR DESCRIPTION
**Pull request by djmisterjon**

### CODE REVIEW

**Comment by djmisterjon** [comment]
in my context
```javascript
    ContainerSpine.prototype.asignParentGroups = function() {
   
        this.d.hackAttachmentGroups("_n", PIXI.lights.normalGroup, PIXI.lights.diffuseGroup); // (nameSuffix, group_n, group_d)
    };
```

**Comment by djmisterjon** [comment]
ivan i have to check something with bizard variable name which not at all affair here.
I think I fucked somewhere I don't understand that we are 2 typescript with different variable name!

**Comment by djmisterjon** [comment]
ho so it is a solution because it is not possible to affect **PIXI.lights.normalGroup** to slots and affect  **PIXI.lights.diffuseGroup** to the spine container.
We need also affect **PIXI.lights.diffuseGroup** to each slots or we can not get rendering.
if a better solution your welcome

**Comment by ivanpopelyshev** [comment]
Ok, got it. the problem is that pixi-spine.js also chnged in this commmit.

**Pull request merged**
