### PR TITLE
Added return before calling next callback

### PR DESCRIPTION
**Pull request by krzysztof-o**

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
Just. Why?

**Comment by krzysztof-o** [comment]
When you provide atlas file in metadata it shouldn't load .atlas file. Without return it goes further and load the atlas file

**Comment by ivanpopelyshev** [comment]
ah, right. I'm stupid. Thank you very much!

**Comment by ivanpopelyshev** [comment]
I'm gonna add hackTextureBySlotName(...) today, please check it out later :)

**Comment by krzysztof-o** [comment]
you're welcome ;)

**Comment by ivanpopelyshev** [comment]
We are starting new html5 gamedev slack . Would you like to join? If so, tell me your email

**Comment by krzysztof-o** [comment]
sure, count me in krzysztof.opalka@gmail.com

**Pull request merged**
