### PR TITLE
Create skeleton data from raw atlas.

### PR DESCRIPTION
**Pull request by congtung10t2**

### CODE REVIEW

**Comment by congtung10t2** [comment]
The main reason is currently we always add atlas with same name with json file that make game will always load atlas file. but we actually can preload atlas file then load json seperate. 
Atlas file that export from spine2D.

**Comment by darting** [comment]
Hi @ivanpopelyshev, What do you think about this pull request?

**Comment by ivanpopelyshev** [comment]
Oh, I didnt see it yet :)

**Comment by ivanpopelyshev** [comment]
Done, version 1.5.13 in npm.

**Pull request merged**
