### PR TITLE
Clipping no longer breaks when the attachment is removed via a detach key

### PR DESCRIPTION
**Pull request by jmlee2k**
Clipping works fine as long as the attachment is always there, but if detaching it during an animation, it breaks.

It APPEARS that this was a simple fix.  I did a few small tests (keying multiple attach and detach keys), and everything seems to work as expected.

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
I suggest to patch line 358 instead. I hope you dont put anything else except clipping attachments in that slot, our runtime certainly wont survive it.

**Comment by jmlee2k** [comment]
You're suggesting to change this line?

`if (slot.currentGraphics)` 
to 
`if (clippingAttachment && slot.currentGraphics)`

If so, we would need to keep the modification on line 371 as well, right?  That way it can get into the else and set the child to the container instead of the masked container?

Makes sense to me, so I'm happy to change it providing I understand your suggestion correctly.

**Comment by ivanpopelyshev** [comment]
no, `slot.currentGraphics && slot.attachment`, But please check if it actually works and does not render white colored graphics by some strange reason.

**Comment by jmlee2k** [comment]
Yeah, that's what I meant, sorry.  I'll test it out and make a new PR.

**Pull request closed without merging**
