### PR TITLE
Fix #208 - If endSlot is default, don't set self as endSlot.

### LINKED ISSUE #208: Clipping mask does not apply the correct mask if the mask itself was marked as end slot.
In Spine, if the clipping mask itself was marked as the end slot, everything in the draw order above it applies the mask. In pixi-spine, nothing applies the mask in this case.

I'm going to investigate it, see if I am wrong somehow. Gonna make a PR if needed.

We're on version 3.6.48, PIXI Spine is on a recent master pull.

### PR DESCRIPTION
**Pull request by Querijn**

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
Does it actually work? I dont like the fact that its changing attachment in runtime.

**Comment by Querijn** [comment]
Neither do I, but I reported this is what I reported a month ago to be working. To be sure, I'll check again and comment here.

**Comment by Querijn** [comment]
Before:
before
After:
works

Could potentially use more test cases though.

**Comment by ivanpopelyshev** [comment]
Good, ill look for better fix before i merge this thing.

**Comment by Querijn** [comment]
That sounds great. Thanks for your time.

**Comment by ivanpopelyshev** [comment]
I'll make sure to fix it before next time i synchronize pixi-spine and spine-ts so you wont have to use backwards version ;)

**Comment by ivanpopelyshev** [comment]
done, 1.5.11

**Pull request merged**
